#!/bin/sh
sleep 1
echo "\033[1;33mBAIXANDO PACOTES NECESSÁRIOS\033[m"
echo " "

#Usando nas feramentas 
pkg install wget -y
pkg install sl -y
pkg install figlet -y
pkg install nmap -y

sleep 1
clear
echo "\033[1;33m[+]Baixando python...\033[m"

# Baixando o Python
pkg install python -y
pkg install python-pip -y

sleep 1
clear
echo "\033[1;33m[+]Baixando bibliotecas necessarias...\033[m"

# Bibliotecas Python
pip install faker
pip install requests

clear
echo "\033[1;33m[+]INSTALANDO...\033[m"
sleep 2
echo "\033[1;33m[+]PRONTO.\033[m"
sleep 1
echo "\033[1;32m "
sl

# Executa o script Python
python3 main.py
